version: '2'

vars:
    CURDIR:
        sh: pwd
    TESTDIR:
        sh: echo "$(pwd)/test"
    SRCDIR:
        sh: echo "$(pwd)/src"

tasks:
    default:
        - task: test

    test:
        cmds:
            - cmd: cd {{.TESTDIR}} && bats argparse_test.bats
            - cmd: cd {{.TESTDIR}} && ./test1.sh -d
            - cmd: cd {{.TESTDIR}} && ./test2.sh -b
            - cmd: cd {{.TESTDIR}} && ./test3.sh -s hello
